### ISSUE TITLE
pagination of inlined resources?

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cc-api-v3-style-guide#41]
what if there are a bunch of related resources? v2 api I believe limits how many inlined resources are returned.

**Comment by zrob** [comment]
yeah, we should have this, it could look something like

```
"included": {
  "apps": {
     pagination: {}
     resources: {}
   }
}
```

**Comment by gberche-orange** [comment]
would be nice to include an example of a pagination request on a related resource inclusion request (e.g,

/v2/spaces/ab09cd29-9420-f021-g20d-123431420768?include=apps&include_apps_order_by=-state,-date)

**Comment by gberche-orange** [comment]
a small typo on 

https://github.com/cloudfoundry/cc-api-v3-style-guide#pagination-of-related-resources

`GET /v3/apps/:guid?include=space,organization`

with pluralized resource name should be `GET /v3/apps/:guid?include=spaces,organizations`

**Comment by dieucao** [comment]
https://www.pivotaltracker.com/story/show/103430116

**Comment by jberkhahn** [comment]
@gberche-orange 
The example was broken, but it's actually the response keys were incorrect. The request is single because apps only have one space, spaces have one org, etc, but the response must be pluralized as it's an indeterminate number of the resources returned. It's been fixed.

@cppforlife 
We've also since written up a proposal for paginated resources.

**Comment by dieucao** [comment]
Closing this issue.  If there are concerns about the proposal, please open a new issue.
